version: 3.0.0

services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: realtime

  adminer:
    image: adminer
    ports:
      - 8080:8080
