export const TYPES = {
    IUsersUseCase: Symbol.for('IUsersUseCase'),
    IQuizUseCase: Symbol.for('IQuizUseCase'),
    IQuestionUseCase: Symbol.for('IQuestionUseCase'),
    IAnswerUseCase: Symbol.for('IAnswerUseCase'),
    ExpressRestPort: Symbol.for('ExpressRestPort'),
    IUserRepository: Symbol.for('IUserRepository'),
    IQuizRepository: Symbol.for('IQuizRepository'),
    IQuestionRepository: Symbol.for('IQuestionRepository'),
    IAnswerRepository: Symbol.for('IAnswerRepository'),
    CardRepository: Symbol.for('CardRepository'),
    IUuidService: Symbol.for('UuidService'),
    CardService: Symbol.for('CardService'),
    DateService: Symbol.for('DateService'),
    IRoomsUseCase: Symbol.for('IRoomsUseCase'),
    IRoomRepository: Symbol.for('IRoomRepository'),
    ISocketPortInterface: Symbol.for('ISocketPortInterface'),
    IPassword: Symbol.for('IPassword'),
    IJsonWebToken: Symbol.for('IJsonWebToken'),
    ITestRepository: Symbol.for('ITestRepository'),
    IRoomAnswerRepository: Symbol.for('IRoomAnswerRepository'),
}
